version: "3.6"

services:
  currency-conversion-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:${CCY_CONVERSION_SERVER_PORT}"
    network_mode: host
    environment:
      RDS_HOST_NAME: currency-conversion-db
    container_name: currency-conversion-service-cn
    networks:
      - currency-bridge
    depends_on:
      - currency-conversion-db

  currency-conversion-db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    env_file:
      - .env
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    container_name: ccy-conversion-data-cn
    networks:
      - currency-bridge
    volumes:
      - ccy-conversion-mysql-db-volume:/var/lib/mysql

networks:
  currency-bridge:

volumes:
  ccy-conversion-mysql-db-volume:
