version: "3.6"

services:
  ccy-conversion-backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:${SERVER_PORT}"
    environment:
      RDS_HOST_NAME: ccy-conversion-db
    container_name: ccy-conversion-services
    networks:
      - ccy-conversion-bridge
    depends_on:
      - ccy-conversion-db

  ccy-conversion-db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    env_file:
      - .env
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    container_name: ccy-conversion-data
    networks:
      - ccy-conversion-bridge
    volumes:
      - ccy-conversion-mysql-db-volume:/var/lib/mysql

networks:
  ccy-conversion-bridge:

volumes:
  ccy-conversion-mysql-db-volume:
